### ISSUE TITLE
Support for Opentracing

### ISSUE THREAD

**Issue by dzonekl** [AxonIQ/axoniq-axonhub-client#19]
Hi, 

I am working on implementing Opentracing in the Axonframework, 
see this issue: (Which is also about sleuth, but the challenge is similar): 

https://github.com/AxonFramework/AxonFramework/issues/257

See also a discussion on opentracing-java regarding this very same issue: 
https://github.com/opentracing/opentracing-java/issues/318

See a log trace in the above issue, where we see a thread named `ault-executor-0`, which should really read `grpc-default-executor-0` after this thread, opentracing will spin a new trace, likely because the spancontext is not propagated by the Grpc executor service. 

My suspicion is that, the Trace context is not propagated by the NettyChannel when creating threads. 
I noticed the PlatformConnectionManager, initialises a channel, with the default executor, and that it is also not possible to install custom Interceptors. 

I would like to create a PR on the axonhub client, where (1) I use a context aware executor service, which could propagate the context and (2) install an opentracing interceptor 

(1) This is a candidate Executor Service: 

https://github.com/talsma-ict/context-propagation

(2) This is the candidate interceptor: 

https://github.com/opentracing-contrib/java-grpc

Now, my question for now is, please provide guidance on how to contribute this and also, I can not build the project locally, as a private nexus is used, so how do I contribute to the Axonhub client? 

Thank You, 
Christophe Bouhier

**Comment by abuijze** [comment]
The AxonHub client has been deprecated in favor of the AxonServer Connector. OpenTracing has since also been implemented in an extension for AxonFramework
